fix: Correct script modifying the project files to replace whatever the targetframeworkversion is.

diff --git a/.github/workflows/static-code-analysis.yml b/.github/workflows/static-code-analysis.yml
--- a/.github/workflows/static-code-analysis.yml
+++ b/.github/workflows/static-code-analysis.yml
@@ -42,6 +42,16 @@ jobs:
           targetPlatform: StandaloneLinux64
         continue-on-error: true
 
+
+      - name: Locate Unity Editor
+        run: |
+          echo "Searching for Unity executable..."
+          find / -type f -name "Unity" 2>/dev/null || echo "Unity executable not found"
+        continue-on-error: true
+
+      - name: Print environment variables
+        run: env
+
       # Modifies the project files after they have been generated
       - name: Modify Project Files to Target .NET Standard
         run: |
